name: redid
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl_phone_number_input: ^0.7.0+2
  flutter_otp_text_field: ^1.0.0
  font_awesome_flutter: ^9.2.0
  argon_buttons_flutter: ^1.1.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.4

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
 #  - assets/icons/password.png
    - assets/icons/forgotpass.png
    - assets/icons/otp.svg
    - assets/icons/accountpass.svg
    - assets/icons/wallet.svg

  fonts:
    - family: Chiller
      fonts:
        - asset: assets/fonts/Chiller.ttf
          weight: 700
    - family: Book-Antiqua
      fonts:
        - asset: assets/fonts/book-antiqua.ttf
