name: redid
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.6+65

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  intl_phone_number_input: ^0.7.0+2
  flutter_otp_text_field: ^1.0.0
  font_awesome_flutter: ^9.2.0
  argon_buttons_flutter: ^1.1.0
  card_swiper: ^1.0.4
  google_fonts: ^2.1.0
  http: ^0.13.4
  datetime_picker_formfield: ^2.0.0
  fl_chart: ^0.40.2
  settings_ui: ^1.0.0
  flutter_slidable: ^0.6.0
  material_dialogs: ^1.1.1
  dotted_border: ^2.0.0+1
  badges: ^2.0.1
  flutter_rating_bar: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: "launcher_icon"
  ios: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/logo.png
    - assets/icons/forgotpass.png
    - assets/icons/otp.svg
    - assets/icons/accountpass.svg
    - assets/icons/wallet.svg
    - assets/icons/hlogo.png
    - assets/icons/b1.svg
    - assets/icons/b2.svg
    - assets/icons/b3.svg
    - assets/icons/b4.svg
    - assets/icons/b5.svg
    - assets/icons/b6.svg
    - assets/icons/help.svg
    - assets/icons/helpchat.svg
    - assets/icons/helpemail.svg
    - assets/icons/helpfaq.svg
    - assets/icons/silver.svg
    - assets/icons/gold.svg
    - assets/icons/platinum.svg
    - assets/icons/bronze.svg
    - assets/icons/crown.svg
    - assets/icons/coupon.svg
    - assets/icons/workplace.svg
    - assets/icons/watch.svg
    - assets/icons/affiliate.svg
    - assets/icons/ratings.svg

  fonts:
    - family: Chiller
      fonts:
        - asset: assets/fonts/Chiller.ttf
          weight: 700
    - family: Book-Antiqua
      fonts:
        - asset: assets/fonts/book-antiqua.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica.ttf
    - family: Helvetica-Bold
      fonts:
        - asset: assets/fonts/Helvetica-Bold.ttf

