name: redid
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2+25

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  intl_phone_number_input: ^0.7.0+2
  flutter_otp_text_field: ^1.0.0
  font_awesome_flutter: ^9.2.0
  argon_buttons_flutter: ^1.1.0
  card_swiper: ^1.0.4
  google_fonts: ^2.1.0
  http: ^0.13.4
  datetime_picker_formfield: ^2.0.0
  fl_chart: ^0.40.2
  settings_ui: ^1.0.0
  flutter_slidable: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/icons/forgotpass.png
    - assets/icons/otp.svg
    - assets/icons/accountpass.svg
    - assets/icons/wallet.svg
    - assets/icons/banner1.svg
    - assets/icons/banner2.svg
    - assets/icons/banner3.svg
    - assets/icons/banner4.svg
    - assets/icons/banner5.svg
    - assets/icons/banner6.svg
    - assets/icons/banner7.svg

  fonts:
    - family: Chiller
      fonts:
        - asset: assets/fonts/Chiller.ttf
          weight: 700
    - family: Book-Antiqua
      fonts:
        - asset: assets/fonts/book-antiqua.ttf

